### ISSUE TITLE
where is statsd in this?

### ISSUE THREAD

**Issue by babatundebusari** [nickstenning/docker-graphite#9]
#1. Where is statsd? 

#2. and if am trying to send metrics from collectd, how does this fit in here?

much thanks

**Comment by Haegin** [comment]
I don't know anything about `collectd` so I can't help you with point 2, but as for point 1 StatsD isn't included in this container so you'll need to run a second container that provides StatsD. In my case I'm using statsite instead of StatsD and am using `docker-compose` to connect the two containers together (along with several other containers such as one for Grafana etc). Hopefully this helps.

**Comment by babatundebusari** [comment]
i fixed this 
Thanks
